version: '2'

x-ssl-service:
  volumes:
    - &ssl-cert
      ./letsencrypt/etc/live/${DOMAIN_NAME}/fullchain.pem:/fullchain.pem:ro
    - &ssl-key
      ./letsencrypt/etc/live/${DOMAIN_NAME}/privkey.pem:/privkey.pem:ro

services:
  pihole:
    container_name: pihole
    image: docker.io/pihole/pihole:latest
    restart: unless-stopped
    # NOTE: if you also want to access pihole via plaintext DNS query,
    # uncomment the lines below.
    # WARNING: Only enable these if you run your server in a LAN.
    # ports:
    #   - 53:53/tcp
    #   - 53:53/udp
    #   - 67:67/udp
    environment:
      - TZ=${TZ}
      - DNS1=172.30.1.2
      - DNS2=no
      - VIRTUAL_HOST=${PIHOLE_DOMAIN_NAME}
    volumes:
      - ./pihole/:/etc/pihole/
      - ./dnsmasq.d/:/etc/dnsmasq.d/
    dns: 127.0.0.1
    depends_on:
      - coredns-backend
    networks:
        default:
            ipv4_address: 172.30.1.1

  coredns-backend:
    image: docker.io/coredns/coredns
    container_name: coredns-backend
    volumes:
      - ./Corefile.backend:/Corefile
    networks:
        default:
            ipv4_address: 172.30.1.2

  ouroboros:
    container_name: ouroboros
    image: docker.io/pyouroboros/ouroboros:latest
    restart: unless-stopped
    dns: 172.30.1.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SELF_UPDATE=true
      - CLEANUP=true
      - INTERVAL=3600

  pomerium:
    image: docker.io/pomerium/pomerium:latest
    container_name: pomerium
    restart: unless-stopped
    dns: 172.30.1.1
    hostname: ${POMERIUM_DOMAIN_NAME}
    depends_on:
      - pihole
    environment:
      - IDP_PROVIDER=google
      - IDP_PROVIDER_URL=https://accounts.google.com
      - IDP_CLIENT_ID=${POMERIUM_CLIENT_ID}
      - IDP_CLIENT_SECRET=${POMERIUM_CLIENT_SECRET}
      - AUTHENTICATE_SERVICE_URL=https://${POMERIUM_DOMAIN_NAME}
      - SHARED_SECRET=${POMERIUM_SHARED_SECRET}
      - COOKIE_SECRET=${POMERIUM_COOKIE_SECRET}
      - CERTIFICATE_FILE=/fullchain.pem
      - CERTIFICATE_KEY_FILE=/privkey.pem
    volumes:
      - *ssl-cert
      - *ssl-key
      - ./pomerium/config.yaml:/pomerium/config.yaml:ro
    ports:
      - 443:443
      - 80:80

  autoheal:
    image: docker.io/willfarrell/autoheal
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  coredns:
    image: docker.io/coredns/coredns
    container_name: coredns
    restart: always
    environment:
      - GODEBUG=tls13=1
    volumes:
      - ./Corefile:/Corefile
      - *ssl-cert
      - *ssl-key
    ports:
      - 853:853

networks:
    default:
        external:
            name: infra_network
