services: all
pomerium_debug: true
http_redirect_addr: :80

policy:
  - from: https://pihole.example.com
    to: http://pihole
    timeout: 10m
    allowed_users:
      - YOUR_GMAIL_ACCOUNT
  - from: https://dns.example.com
    to: https://coredns
    allow_public_unauthenticated_access: true
    # TODO: change to tls_server_name once
    # https://github.com/pomerium/pomerium/pull/297 is merged.
    tls_skip_verify: true
